//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Base.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Common {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Common() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Base.Resources.Common", typeof(Common).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CAS Number.
        /// </summary>
        public static string CASNumber {
            get {
                return ResourceManager.GetString("CASNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chemical Formula.
        /// </summary>
        public static string ChemicalFormula {
            get {
                return ResourceManager.GetString("ChemicalFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Code.
        /// </summary>
        public static string ColorCode {
            get {
                return ResourceManager.GetString("ColorCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concentration.
        /// </summary>
        public static string Concentration {
            get {
                return ResourceManager.GetString("Concentration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created At.
        /// </summary>
        public static string CreatedAt {
            get {
                return ResourceManager.GetString("CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted At.
        /// </summary>
        public static string DeletedAt {
            get {
                return ResourceManager.GetString("DeletedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Time.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid for {1}..
        /// </summary>
        public static string ErrorMessage_AttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_AttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a maximum length of &apos;{1}&apos;..
        /// </summary>
        public static string ErrorMessage_MaxLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string or array type with a minimum length of &apos;{1}&apos;..
        /// </summary>
        public static string ErrorMessage_MinLength {
            get {
                return ResourceManager.GetString("ErrorMessage_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for the &apos;{0}&apos; parameter or property was not provided..
        /// </summary>
        public static string ErrorMessage_MissingBindRequiredValue {
            get {
                return ResourceManager.GetString("ErrorMessage_MissingBindRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value is required..
        /// </summary>
        public static string ErrorMessage_MissingKeyOrValue {
            get {
                return ResourceManager.GetString("ErrorMessage_MissingKeyOrValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A non-empty request body is required..
        /// </summary>
        public static string ErrorMessage_MissingRequestBodyRequiredValue {
            get {
                return ResourceManager.GetString("ErrorMessage_MissingRequestBodyRequiredValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is not valid..
        /// </summary>
        public static string ErrorMessage_NonPropertyAttemptedValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_NonPropertyAttemptedValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value is invalid..
        /// </summary>
        public static string ErrorMessage_NonPropertyUnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_NonPropertyUnknownValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field must be a number..
        /// </summary>
        public static string ErrorMessage_NonPropertyValueMustBeANumber {
            get {
                return ResourceManager.GetString("ErrorMessage_NonPropertyValueMustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is not a valid phone number..
        /// </summary>
        public static string ErrorMessage_NotValidPhone {
            get {
                return ResourceManager.GetString("ErrorMessage_NotValidPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be between {1} and {2}..
        /// </summary>
        public static string ErrorMessage_Range {
            get {
                return ResourceManager.GetString("ErrorMessage_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The {0} field is required..
        /// </summary>
        public static string ErrorMessage_Required {
            get {
                return ResourceManager.GetString("ErrorMessage_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a maximum length of {1}..
        /// </summary>
        public static string ErrorMessage_StringLengthMax {
            get {
                return ResourceManager.GetString("ErrorMessage_StringLengthMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a string with a minimum length of {2} and a maximum length of {1}..
        /// </summary>
        public static string ErrorMessage_StringLengthMinMax {
            get {
                return ResourceManager.GetString("ErrorMessage_StringLengthMinMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied value is invalid for {0}..
        /// </summary>
        public static string ErrorMessage_UnknownValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_UnknownValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid..
        /// </summary>
        public static string ErrorMessage_ValueIsInvalid {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The field {0} must be a number..
        /// </summary>
        public static string ErrorMessage_ValueMustBeANumber {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueMustBeANumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value &apos;{0}&apos; is invalid..
        /// </summary>
        public static string ErrorMessage_ValueMustNotBeNull {
            get {
                return ResourceManager.GetString("ErrorMessage_ValueMustNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expired.
        /// </summary>
        public static string Expired {
            get {
                return ResourceManager.GetString("Expired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Path.
        /// </summary>
        public static string FilePath {
            get {
                return ResourceManager.GetString("FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Form_Actions {
            get {
                return ResourceManager.GetString("Form_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to List.
        /// </summary>
        public static string Form_BackToList {
            get {
                return ResourceManager.GetString("Form_BackToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Form_Cancel {
            get {
                return ResourceManager.GetString("Form_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string Form_Clear {
            get {
                return ResourceManager.GetString("Form_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Form_Create {
            get {
                return ResourceManager.GetString("Form_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Form_Delete {
            get {
                return ResourceManager.GetString("Form_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Form_Details {
            get {
                return ResourceManager.GetString("Form_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---Select---.
        /// </summary>
        public static string Form_DropDownSelect {
            get {
                return ResourceManager.GetString("Form_DropDownSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Form_Edit {
            get {
                return ResourceManager.GetString("Form_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Form_Save {
            get {
                return ResourceManager.GetString("Form_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Form_Search {
            get {
                return ResourceManager.GetString("Form_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding.
        /// </summary>
        public static string Funding {
            get {
                return ResourceManager.GetString("Funding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Handed Over.
        /// </summary>
        public static string HandedOver {
            get {
                return ResourceManager.GetString("HandedOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hazardous.
        /// </summary>
        public static string Hazardous {
            get {
                return ResourceManager.GetString("Hazardous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Hazardous.
        /// </summary>
        public static string IsHazardous {
            get {
                return ResourceManager.GetString("IsHazardous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Name.
        /// </summary>
        public static string MeasurementName {
            get {
                return ResourceManager.GetString("MeasurementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Value.
        /// </summary>
        public static string MeasurementValue {
            get {
                return ResourceManager.GetString("MeasurementValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Molecular Weight.
        /// </summary>
        public static string MolecularWeight {
            get {
                return ResourceManager.GetString("MolecularWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        public static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirements.
        /// </summary>
        public static string Requirements {
            get {
                return ResourceManager.GetString("Requirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Safety Notes.
        /// </summary>
        public static string SafetyNotes {
            get {
                return ResourceManager.GetString("SafetyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serial Code.
        /// </summary>
        public static string SerialCode {
            get {
                return ResourceManager.GetString("SerialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Time.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Conditions.
        /// </summary>
        public static string StorageConditions {
            get {
                return ResourceManager.GetString("StorageConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test.
        /// </summary>
        public static string test {
            get {
                return ResourceManager.GetString("test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit.
        /// </summary>
        public static string Unit {
            get {
                return ResourceManager.GetString("Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated At.
        /// </summary>
        public static string UpdatedAt {
            get {
                return ResourceManager.GetString("UpdatedAt", resourceCulture);
            }
        }
    }
}
