//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Shared {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class _Navigation {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal _Navigation() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.Views.Shared._Navigation", typeof(_Navigation).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }

        public static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }

        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }

        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }

        public static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }

        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }

        public static string UserManagement {
            get {
                return ResourceManager.GetString("UserManagement", resourceCulture);
            }
        }

        public static string Establishments {
            get {
                return ResourceManager.GetString("Establishments", resourceCulture);
            }
        }

        public static string LookupData {
            get {
                return ResourceManager.GetString("LookupData", resourceCulture);
            }
        }
    }
}
