<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <EmbeddedResource Update="Views\Shared\_Layout.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>_Layout.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Shared\_Navigation.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>_Navigation.Designer.cs</LastGenOutput>
      </EmbeddedResource>
      <EmbeddedResource Update="Views\Establishments\Index.resx">
        <Generator>PublicResXFileCodeGenerator</Generator>
        <LastGenOutput>Index.Designer.cs</LastGenOutput>
      </EmbeddedResource>
    </ItemGroup>

    <ItemGroup>
      <Compile Update="Views\Shared\_Layout.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>_Layout.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Shared\_Navigation.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>_Navigation.resx</DependentUpon>
      </Compile>
      <Compile Update="Views\Establishments\Index.Designer.cs">
        <DesignTime>True</DesignTime>
        <AutoGen>True</AutoGen>
        <DependentUpon>Index.resx</DependentUpon>
      </Compile>
    </ItemGroup>

</Project>
