//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.LookupData {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LookupDataIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LookupDataIndex() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Views.LookupData.LookupDataIndex", typeof(LookupDataIndex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new document type.
        /// </summary>
        public static string Add_new_document_type {
            get {
                return ResourceManager.GetString("Add new document type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new experiment types.
        /// </summary>
        public static string Add_new_experiment_types {
            get {
                return ResourceManager.GetString("Add new experiment types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new institute type.
        /// </summary>
        public static string Add_new_institute_type {
            get {
                return ResourceManager.GetString("Add new institute type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new project type.
        /// </summary>
        public static string Add_new_project_type {
            get {
                return ResourceManager.GetString("Add new project type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new task type.
        /// </summary>
        public static string Add_new_task_type {
            get {
                return ResourceManager.GetString("Add new task type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document types.
        /// </summary>
        public static string Document_Types {
            get {
                return ResourceManager.GetString("Document Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experiment types.
        /// </summary>
        public static string Experiment_types {
            get {
                return ResourceManager.GetString("Experiment types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute types.
        /// </summary>
        public static string Institute_types {
            get {
                return ResourceManager.GetString("Institute types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lookup data.
        /// </summary>
        public static string Lookup_Data {
            get {
                return ResourceManager.GetString("Lookup Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found.
        /// </summary>
        public static string Not_found {
            get {
                return ResourceManager.GetString("Not found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project types.
        /// </summary>
        public static string Project_types {
            get {
                return ResourceManager.GetString("Project types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Task types.
        /// </summary>
        public static string Task_Types {
            get {
                return ResourceManager.GetString("Task Types", resourceCulture);
            }
        }
    }
}
