//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources.Views.Establishments {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EstablishmentsIndex {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EstablishmentsIndex() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("App.Resources.Views.Establishments.Index", typeof(EstablishmentsIndex).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }

        public static string Institutes {
            get {
                return ResourceManager.GetString("Institutes", resourceCulture);
            }
        }

        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }

        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }

        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }

        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }

        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }

        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }

        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }

        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }

        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }

        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }

        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }

        public static string NoInstitutesFound {
            get {
                return ResourceManager.GetString("NoInstitutesFound", resourceCulture);
            }
        }

        public static string AddNewInstitute {
            get {
                return ResourceManager.GetString("AddNewInstitute", resourceCulture);
            }
        }
    }
}
